name: GH CLI smoke test
on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    # Set GH_TOKEN for all steps in this job
    env:
      # Prefer an org secret with repo + admin:org. Fallback to the workflow token if not set.
      GH_TOKEN: ${{ secrets.ADMIN_PAT != '' && secrets.ADMIN_PAT || github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: Show gh version
        run: gh --version

      - name: Auth status (will use GH_TOKEN automatically)
        run: gh auth status

      - name: Who am I?
        run: gh api user --jq .login
